name: DotNet Build And Test
run-name: Workflow triggered by ${{github.actor}}
on:
  push:
    branches: [$default-branch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
