#https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push

# This workflow triggers on the Push events on the main branch or any branch whose name starts with "task/"

# Push event has been used along with branches filter here.

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet

# The push event runs your workflow when you push a commit or tag,
# or when you create a repository from a template

name: Push Workflow
on:
  push:
    branches:
      - "main"
      - "task/**"
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: |
          echo "Hello!"
