# Issues events used along with Activity type [opened]

name: Issues Workflow
on:
  workflow_dispatch:
  issues:
    types: [opened]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print the Event
        run: |
          echo "${{ toJSON(github.event)}}"
