# Github Context
# https://docs.github.com/en/actions/learn-github-actions/contexts#github-context

# Expressions
# https://docs.github.com/en/actions/learn-github-actions/expressions

name: Access Context Workflow
on:
  workflow_dispatch:
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Output Context
        run: |
          echo "${{ toJSON(github) }}"
