name: Deployment
on: workflow_dispatch
jobs:
  test:
    environment: testing
    runs-on: ubuntu-latest
    env:
      MONGODB_CLUSTER_ADDRESS: cluster0.qmen2am.mongodb.net
      MONGODB_USERNAME: ${{secrets.MONGODB_USERNAME}}
      MONGODB_PASSWORD: ${{secrets.MONGODB_PASSWORD}}
      PORT: 8080
      WORKING_DIRECTORY: "${{ github.workspace }}/EnvironmentVariables/Project"
    defaults:
      run:
        shell: bash
        working-directory: ${{env.WORKING_DIRECTORY}}
    steps:
      - name: Get Code
        uses: actions/checkout@v3

        # if cache hit => restoring cache identified by the key from github owned storage to the path ~/.npm
        # if cache miss => when the job is done, copy the contents present in the path '~/.npm' into cache so that it can be used in subsequent jobs if used again or used in subsequent runs
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci #
      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:$PORT
      - name: Run tests
        run: npm test
      - name: Output information
        run: echo "..."
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |
          echo "..."
