# Note:

# This workflow serves as an instructional example to showcase the concept of reusable workflows.
# It is not intended to fulfill any specific real-world use case, but rather to demonstrate how reusable workflows can be structured and utilized effectively within GitHub Actions

name: Reusable Workflow - Caller Workflow
on: workflow_dispatch
jobs:
  first-job:
    uses: "./.github/workflows/25reusable-called-workflow.yml"
    with:
      text-to-print: "Hello, World"
      colour: blue
