# Note:

# This workflow serves as an instructional example to showcase the concept of reusable workflows.
# It is not intended to fulfill any specific real-world use case, but rather to demonstrate how reusable workflows can be structured and utilized effectively within GitHub Actions

name: Reusable Workflow - Caller Workflow
on: workflow_dispatch
jobs:
  first-job:
    uses: "./.github/workflows/25reusable-called-workflow.yml"
    with:
      text-to-print: "Hello, World"
      colour: blue
  second-job:
    uses: "./.github/workflows/27reusable-called-workflow-2.yml"
    with:
      operand1: 10
      operand2: 5
      operation: "+"
  third-job:
    needs: second-job
    runs-on: ubuntu-latest
    steps:
      - name: Print Sum
        run: |
          echo "${{needs.second-job.outputs.sum}}"
