name: Custom JS Action Workflow
on: workflow_dispatch
jobs:
  hello-word-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Print Hello
        uses: "./.github/actions/hello-world-javascript-action"
        with:
          who-to-greet: ${{github.triggering_actor}}
