name: Multiple Events Workflow
run-name: Workflow triggered for ${{github.event_name}}

# If we specify multiple events,
# only one of those events needs to occur to trigger your workflow.
# If multiple triggering events for your workflow occur at the same time,
# multiple workflow runs will be triggered.

# gh workflow run run-tests.yml -f logLevel=warning -f tags=false -f environment=staging
# type of inputs supported by workflow_dispatch => string, number, boolean, environment and choice
# inputs an be accessed ${{inputs}} context or ${{github.event.inputs.}}

on: [workflow_dispatch, push]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: "hello world"
        run: echo "Hello, World"
