name: Environments-Workflow
run-name: workflow triggered by ${{ github.triggering_actor}}
on: workflow_dispatch
jobs:
  staging-job:
    runs-on: ubuntu-latest
    environment: staging_environment
    env:
      VARIABLE_1: ${{vars.NOT_A_SECRET}}
    steps:
      - name: display variable
        run: |
          echo "${{env.VARIABLE_1}}"
      - name: display variable again
        run: |
          echo "$VARIABLE_1"
