name: Scripts Workflow
run-name: workflow triggered by ${{github.actor}}
on: [workflow_dispatch]
jobs:
  scripts-job:
    runs-on: ubuntu-latest
    steps:
      - name: inline-script
        run: echo "Hello!"

      - name: check-out-code
        uses: actions/checkout@v4
      - name: ls
        run: ls -la
      - name: make-the-script-file-executable
        working-directory: Scripts
        run: chmod +x hello.sh
      - name: run-the-script
        working-directory: Scripts
        run: ./hello.sh
