name: artifacts test
on:
 workflow_dispatch
jobs:
  first-job: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: print GITHUB_WORKSPACE
        run: |
          echo "$GITHUB_WORKSPACE"
      - name: List Files and Folder recursively
        run: find $GITHUB_WORKSPACE
      - name: List Files and Folder
        run: ls
      - name: print workspace from context variable
        run: echo "${{ github.workspace }}" 
       
