name: artifacts test
on:
 workflow_dispatch
jobs:
  first-job: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: print GITHUB_WORKSPACE
        run: |
          echo "$GITHUB_WORKSPACE"
      - name: List Files and Folder recursively
        run: find $GITHUB_WORKSPACE
      - name: List Files and Folder
        run: ls
      - name: print workspace from context variable
        run: echo "${{ github.workspace }}" 
      - name: Store Test Results
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-test-results
          path: ${{ github.workspace }}/tests/*//test-results.*
      - name: Store Invalid Results
        uses: actions/upload-artifact@v4
        with:
          name: invalid-artifacts
          path: ${{ github.workspace }}/invalidd/*//test-results.*
