name: Docker Version Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: docker --version
      - name: Print goodbye
        run: docker compose --version
