#Here, PAT requires the read permissions to the organization
# https://docs.github.com/en/rest/teams/members?apiVersion=2022-11-28#list-team-members

name: Get Teams Workflow
on: [workflow_dispatch]
jobs:
  first-job:
    environment: Development
    runs-on: ubuntu-latest
    steps:
      - name: Get Team Members
        run: |
          TOKEN="${{ secrets.READ_TEAM_PAT}}"
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/orgs/tdk-org/teams/tdkorgadmin/members
