name: Parallel Jobs Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: sleep and say hello
        run: |
          echo "sleep for 10 seconds"
          sleep 10
          echo "first - job: Hello!"
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: sleep for 3 seconds and say hi
        run: |
          echo "sleep for 3 seconds"
          sleep 3
          echo "second - job: Hi"
