name: Path Filters Workflow
on:
  push:
    paths:
      - "**/README.md"
    paths-ignore:
      - ".github/workflows/*"
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Message
        run: echo "A README.md file has been updated"
