# Workflow runs if README.md has been changed, then committed and pushed. (README.md is one of the changed files)

name: Path Filters Workflow
on:
  push:
    paths:
      - "**/README.md"
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Message
        run: echo "A README.md file has been updated"
