name: Print PWD Workflow
on:
  workflow_dispatch:
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print pwd
        run: |
          echo "Printing PWD..."
          pwd
      - name: print GITHUB_WORKSPACE
        run: |
          echo "$GITHUB_WORKSPACE"
      - name: List Files and Folder recursively
        run: find $GITHUB_WORKSPACE
      - name: List Files and Folder
        run: ls
