name: Print PWD Workflow
on:
  workflow_dispatch:
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: print pwd
        run: |
          echo "Printing PWD..."
          pwd
      - name: print GITHUB_WORKSPACE
        run: |
          echo "$GITHUB_WORKSPACE"
      - name: List Files and Folder recursively
        run: find $GITHUB_WORKSPACE
      - name: List Files and Folder
        run: ls

  second-job:
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}/JobArtifactsAndOutputs

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Print current working directory
        run: pwd

      - name: List files in working directory
        run: ls
