name: Pull Request Event Workflow
on:
  pull_request:
    types: [opened]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print the Event
        run: |
          echo "${{ toJSON(github.event)}}"
