name: Pull Request Event Workflow
on:
  pull_request:
    types: [opened, assigned]
    branches:
      - main # triggered when PR is targetted to main branch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print the Event
        run: |
          echo "${{ toJSON(github.event)}}"
