#https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push

# This workflow triggers on the Push events on the main branch or any branch whose name starts with "task/"

name: Push Workflow
on:
  push:
    branches:
      - "main"
      - "task/**"
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: |
          echo "Hello!"
