name: Workflow Dispatch Conditional Workflow
on: [workflow_dispatch, push]
jobs:
  first-job:
    runs-on: ubuntu-latest
    name: first-job

    steps:
      - name: Print Message
        run: echo "Hello from First Job"
      - name: Print Event
        run: echo "${{  toJSON(github.event_name) }}"
      - name: Print Git Ref
        run: echo "${{  toJSON(github.ref) }}"

  second-job:
    if: ( github.event_name == 'push' || github.event_name == 'workflow_dispatch' ) && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: second-job
    needs: first-job

    steps:
      - name: Print Message
        run: |
          echo "Hello from Second Job"
