name: Workflow Dispatch Conditional Workflow
on: [workflow_dispatch, push]
jobs:
  first-job:
    runs-on: ubuntu-latest
    name: first-job

    steps:
      - name: Print Message
        run: echo "Hello from First Job"
      - name: Print Event Name
        run: echo "${{  toJSON(github.event_name) }}"
      - name: Print Git Ref
        run: echo "${{  toJSON(github.ref) }}"
      - name: Print Actor
        run: echo "${{ toJSON(github.actor)}}"
      - name: Print Actor Id
        run: echo "${{ toJSON(github.actor_id)}}"
      - name: Print Triggering Actor
        run: echo "${{ toJSON(github.triggering_actor)}}"
      - name: Print Names
        run: echo "${{ fromJSON('["push", "pull_request"]')}}"
      - name: Print Names
        run: echo "${{ contains(fromJSON('["Anand-1912", "Arun-1912"]'), github.triggering_actor)}}"

  second-job:
    #if: ( github.event_name == 'push' || ( github.event_name == 'workflow_dispatch' && github.triggering_actor == 'Anand-1912')) && github.ref == 'refs/heads/main'
    if: ( github.event_name == 'push' || ( github.event_name == 'workflow_dispatch' && contains(fromJSON('["Anand-1912", "Arun-1912"]'), github.triggering_actor))) && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: second-job
    needs: first-job

    steps:
      - name: Print Message
        run: |
          echo "Hello from Second Job"
